### ISSUE TITLE
Salut !

### ISSUE THREAD

**Issue by H2WO4** [Samy8z/TP_WEB#1]
C'est marrant les issues.
C'est vrai que je ne vous en ai pas parlé.
Mais c'est pratique pour faire des propositions en indiquer des erreurs.

Et le Markdown ça marche ici ! ![Ouais](https://e.unicode-table.com/orig/09/4d671611fcf5a88f2ac4ee4edf8e95.png)

On peut aussi référencer des passages dans le code : [ici](https://github.com/Samy8z/TP_WEB/blob/main/README.md#tp_web)

**Comment by H2WO4** [comment]
Et on peut s'engueuler dans les commentaires si on est pas d'accord !

**Comment by Samy8z** [comment]
Il n'y a pas de problème dans mon repo monsieur partez d'ici
